# NumPy

In [1]:
import numpy as np

In [21]:
a = np.array([[2 , 6],
             [2  , 9],
             [3  , 2]])

In [23]:
print(a.shape)

(3, 2)


In [29]:
a1 = np.random.randn(5,2)
print(a1)

[[-0.27917943  0.88963043]
 [ 0.31506899  0.494968  ]
 [ 0.83248827  1.43881473]
 [-2.46236163 -2.01926408]
 [-0.09578764 -1.31197933]]


In [33]:
x = np.ones((3,2))
print(x)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [35]:
adding_two_arrays = a + x
print(adding_two_arrays)

[[ 3.  7.]
 [ 3. 10.]
 [ 4.  3.]]


In [36]:
Ones_1 = np.ones((3,2))
Ones_2 = np.ones((3,2))